# Main section
logLevel = {{ if eq "true" .EnvFiles.Kickoff.DEBUG }}"DEBUG"{{ else }}"ERROR"{{ end }}


# Entry points definition
defaultEntryPoints = ["http", "https"]

[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]
{{- if eq "local" .EnvFiles.Kickoff.ENV }}
[[entryPoints.https.tls.certificates]]
certFile = "tests/{{ .Values.Kickoff.project.virtualhost.local }}.crt"
keyFile = "tests/{{ .Values.Kickoff.project.virtualhost.local }}.key"
{{ end }}

# API backend
[web]
address = ":8080"


# Docker backend
[docker]
endpoint = "unix:///var/run/docker.sock"
{{- range $env, $virtualhost := .Values.Kickoff.project.virtualhost }}
{{- if eq  $env $.EnvFiles.Kickoff.ENV }}
domain = "{{ $virtualhost }}"
{{- end }}
{{- end }}
watch = true
exposedbydefault = false