version: '3.3'

services:
{{- if .Values.Kickoff.mysql }}
  mysql:
    image: mysql:5.7
    container_name: local-{{ .Values.Kickoff.project.name }}-mysql
    restart: unless-stopped
    networks:
      - local_{{ .Values.Kickoff.project.name }}_mysql
    {{- if eq "true" .EnvFiles.Kickoff.MYSQL_ENABLE_PORTS_MAPPING }}
    ports:
      - {{ .EnvFiles.Kickoff.MYSQL_HOST_PORT_TO_MAP }}:3306
    {{- end }}
    environment:
      - MYSQL_USER={{ .Values.Kickoff.mysql.user }}
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
    secrets:
      - mysql_password
      - mysql_root_password
    labels:
      - traefik.enable=false
    volumes:
      - ./mysql/volume:/var/lib/mysql:rw
      - ./mysql/conf.d/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
      - ./mysql/conf.d/utf8mb4.cnf:/etc/mysql/conf.d/utf8mb4.cnf:ro
      - ./mysql/docker-entrypoint-initdb.d/databases.sql:/docker-entrypoint-initdb.d/databases.sql:ro
{{ if eq "local" .EnvFiles.Kickoff.ENV }}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: local-{{ .Values.Kickoff.project.name }}-phpmyadmin
    restart: unless-stopped
    networks:
        - local_{{ .Values.Kickoff.project.name }}_mysql
        - proxy
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=admin
    labels:
      - traefik.backend=local-{{ .Values.Kickoff.project.name }}-phpmyadmin
      {{- range $env, $virtualhost := .Values.Kickoff.project.base_virtualhost }}
      {{- if eq  $env $.EnvFiles.Kickoff.ENV }}
      - traefik.frontend.rule=Host:phpadmin.{{ $virtualhost }}
      {{- end }}
      {{- end }}
      - traefik.docker.network=kickoff_proxy
    volumes:
      - ./phpmyadmin/volume:/sessions:rw
{{ end }}
{{- end }}
secrets:
{{ if .Values.Kickoff.mysql }}
  mysql_password:
    file: ./mysql/.secrets/mysql_password.txt

  mysql_root_password:
    file: ./mysql/.secrets/mysql_root_password.txt
{{ end }}
networks:
{{ if .Values.Kickoff.mysql }}
  local_{{ .Values.Kickoff.project.name }}_mysql:
    driver: bridge
{{ end }}
  proxy:
    external:
      name: kickoff_proxy
