version: '3.3'


services:


  toolbox:
    build:
      context: ./toolbox
      args:
        - UID={{ if eq "linux" .Os }}${UID}{{ else }}1000{{ end }}
    container_name: {{ .EnvFiles.Kickoff.ENV }}-{{ .Values.Kickoff.project.name }}-toolbox
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    networks:
      - {{ .EnvFiles.Kickoff.ENV }}_{{ .Values.Kickoff.project.name }}_toolbox
    environment:
      {{- range $env, $virtualhost := .Values.Kickoff.project.virtualhost }}
      {{- if eq  $env $.EnvFiles.Kickoff.ENV }}
      - VIRTUAL_HOST={{ $virtualhost }}
      {{- end }}
      {{- end }}
      {{- if eq "local" .EnvFiles.Kickoff.ENV }}
      - TRAEFIK_USER={{ .Values.Kickoff.traefik.user }}
      - TRAEFIK_PASSWORD={{ .EnvFiles.Kickoff.TRAEFIK_PASSWORD }}
      {{- end }}
    labels:
      - traefik.enable=false
    volumes:
      - ../app:/var/www/html:rw
      {{- if eq "local" .EnvFiles.Kickoff.ENV }}
      - ./toolbox/self-signed-certificate.sh:/openssl/self-signed-certificate.sh:ro
      - ./traefik/certs:/openssl/certs:rw
      {{- end }}
      {{- if ne "local" .EnvFiles.Kickoff.ENV }}
      - ./toolbox/htdigest.sh:/openssl/htdigest.sh:ro
      - ./traefik/auth:/openssl/auth:rw
      {{ end }}

networks:


  {{ .EnvFiles.Kickoff.ENV }}_{{ .Values.Kickoff.project.name }}_toolbox:
    driver: bridge
