version: '3.3'

services:

  proxy:
    image: traefik:1.3.2-alpine
    container_name: kickoff_proxy
    restart: unless-stopped
    command: --web --docker --docker.domain=my-awesome-project.local --logLevel=DEBUG
    networks:
      - proxy
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /dev/null:/traefik.toml:ro

networks:

  proxy:
    driver: bridge