# |--------------------------------------------------------------------------
# | Proxy blueprint
# |--------------------------------------------------------------------------
# |
# | TODO

version: '3.3'


services:


  proxy:
    image: traefik:1.3.3-alpine
    container_name: kickoff-proxy
    restart: unless-stopped
    command: --web --docker --logLevel={{ if eq "true" .EnvFiles.Kickoff.DEBUG }}DEBUG{{ else }}ERROR{{ end }}
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    labels:
      {{- range $env, $virtualhost := .Values.Kickoff.project.virtualhost }}
      {{- if eq $env $.EnvFiles.Kickoff.ENV }}
      - traefik.frontend.rule=Host:traefik.{{ $virtualhost }}
      {{- end }}
      {{- end }}
      - traefik.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/traefik.toml:ro
      {{- if eq "local" .EnvFiles.Kickoff.ENV }}
      - ./traefik/certs:/tests:ro
      {{ end }}

networks:


  proxy:
    driver: bridge